version: '3'

services:
  api:
    container_name: gs-api
    build: .
    ports:
      - "3000:3000"
      - "9299:9299"
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000
    volumes:
      - ./books:/usr/src/app/books

  frontend:
    container_name: gs-frontend
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"
  
  elasticsearch:
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
      
volumes:
  esdata: